const oracledb = require('oracledb');

async function initializeDatabase() {
  let conn;
  try {
    conn = await oracledb.getConnection({
      user: 'system',
      password: 'Password123',
      connectString: 'localhost/FREEPDB1'
    });

    console.log('Connected to database');

    // テーブルが存在しない場合に作成
    try {
      await conn.execute(`
        CREATE TABLE tbl_users (
          user_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
          user_name VARCHAR2(255) NOT NULL,
          date_of_birth DATE,
          CONSTRAINT pk_users PRIMARY KEY (user_id)
        )
      `);
      console.log('Created tbl_users table');
    } catch (err) {
      if (err.errorNum === 955) {
        console.log('tbl_users table already exists');
      } else {
        throw err;
      }
    }

    try {
      await conn.execute(`
        CREATE TABLE tbl_creators (
          creator_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
          creator_name VARCHAR2(255) NOT NULL,
          creator_type VARCHAR2(20) CHECK (creator_type IN ('SOLO','GROUP')),
          CONSTRAINT pk_creators PRIMARY KEY (creator_id)
        )
      `);
      console.log('Created tbl_creators table');
    } catch (err) {
      if (err.errorNum === 955) {
        console.log('tbl_creators table already exists');
      } else {
        throw err;
      }
    }

    try {
      await conn.execute(`
        CREATE TABLE tbl_artists (
          artist_id NUMBER NOT NULL,
          artist_name VARCHAR2(255) NOT NULL,
          date_of_birth DATE,
          started_at DATE,
          ended_at DATE,
          CONSTRAINT pk_artists PRIMARY KEY (artist_id),
          CONSTRAINT fk_artist_creator
            FOREIGN KEY (artist_id)
            REFERENCES tbl_creators(creator_id)
            ON DELETE CASCADE
        )
      `);
      console.log('Created tbl_artists table');
    } catch (err) {
      if (err.errorNum === 955) {
        console.log('tbl_artists table already exists');
      } else {
        throw err;
      }
    }

    try {
      await conn.execute(`
        CREATE TABLE tbl_groups (
          group_id NUMBER,
          group_name VARCHAR2(255) NOT NULL,
          formation_date DATE,
          dissolution_date DATE,
          CONSTRAINT pk_groups PRIMARY KEY (group_id),
          CONSTRAINT fk_group_creator
            FOREIGN KEY (group_id)
            REFERENCES tbl_creators(creator_id)
            ON DELETE CASCADE
        )
      `);
      console.log('Created tbl_groups table');
    } catch (err) {
      if (err.errorNum === 955) {
        console.log('tbl_groups table already exists');
      } else {
        throw err;
      }
    }

    try {
      await conn.execute(`
        CREATE TABLE tbl_music (
          music_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
          music_title VARCHAR2(255) NOT NULL,
          creator_id NUMBER NOT NULL,
          lyrics_by NUMBER,
          composed_by NUMBER,
          arranged_by NUMBER,
          bpm NUMBER CHECK (bpm BETWEEN 20 AND 400),
          musical_key VARCHAR2(5),
          duration_seconds NUMBER,
          CONSTRAINT pk_music PRIMARY KEY (music_id),
          CONSTRAINT fk_music_creator
            FOREIGN KEY (creator_id)
            REFERENCES tbl_creators(creator_id),
          CONSTRAINT fk_music_lyrics
            FOREIGN KEY (lyrics_by)
            REFERENCES tbl_creators(creator_id),
          CONSTRAINT fk_music_composed
            FOREIGN KEY (composed_by)
            REFERENCES tbl_creators(creator_id),
          CONSTRAINT fk_music_arranged
            FOREIGN KEY (arranged_by)
            REFERENCES tbl_creators(creator_id)
        )
      `);
      console.log('Created tbl_music table');
    } catch (err) {
      if (err.errorNum === 955) {
        console.log('tbl_music table already exists');
      } else {
        throw err;
      }
    }

    try {
      await conn.execute(`
        CREATE TABLE tbl_albums (
          album_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
          album_name VARCHAR2(255) NOT NULL,
          creator_id NUMBER,
          release_date DATE,
          CONSTRAINT pk_albums PRIMARY KEY (album_id),
          CONSTRAINT fk_album_creators
            FOREIGN KEY (creator_id)
            REFERENCES tbl_creators(creator_id)
        )
      `);
      console.log('Created tbl_albums table');
    } catch (err) {
      if (err.errorNum === 955) {
        console.log('tbl_albums table already exists');
      } else {
        throw err;
      }
    }

    try {
      await conn.execute(`
        CREATE TABLE tbl_album_music (
          album_id NUMBER NOT NULL,
          music_id NUMBER NOT NULL,
          track_number NUMBER NOT NULL,
          CONSTRAINT pk_album_music PRIMARY KEY (album_id,track_number),
          CONSTRAINT fk_am_albums
            FOREIGN KEY (album_id)
            REFERENCES tbl_albums(album_id),
          CONSTRAINT fk_am_music
            FOREIGN KEY (music_id)
            REFERENCES tbl_music(music_id),
          CONSTRAINT uq_album_music UNIQUE (album_id,music_id)
        )
      `);
      console.log('Created tbl_album_music table');
    } catch (err) {
      if (err.errorNum === 955) {
        console.log('tbl_album_music table already exists');
      } else {
        throw err;
      }
    }

    try {
      await conn.execute(`
        CREATE TABLE tbl_user_owned_music (
          user_id NUMBER NOT NULL,
          music_id NUMBER NOT NULL,
          CONSTRAINT pk_user_owned_music PRIMARY KEY (user_id, music_id),
          CONSTRAINT fk_uom_users
            FOREIGN KEY (user_id)
            REFERENCES tbl_users(user_id)
            ON DELETE CASCADE,
          CONSTRAINT fk_uom_music
            FOREIGN KEY (music_id)
            REFERENCES tbl_music(music_id)
            ON DELETE CASCADE
        )
      `);
      console.log('Created tbl_user_owned_music table');
    } catch (err) {
      if (err.errorNum === 955) {
        console.log('tbl_user_owned_music table already exists');
      } else {
        throw err;
      }
    }

    try {
      await conn.execute(`
        CREATE TABLE tbl_setlists (
          setlist_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
          setlist_name VARCHAR2(255) NOT NULL,
          user_id NUMBER NOT NULL,
          created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
          deleted_at TIMESTAMP,
          updated_at TIMESTAMP,
          CONSTRAINT pk_setlists PRIMARY KEY (setlist_id),
          CONSTRAINT fk_setlist_users
            FOREIGN KEY (user_id)
            REFERENCES tbl_users(user_id)
            ON DELETE CASCADE
        )
      `);
      console.log('Created tbl_setlists table');
    } catch (err) {
      if (err.errorNum === 955) {
        console.log('tbl_setlists table already exists');
      } else {
        throw err;
      }
    }

    try {
      await conn.execute(`
        CREATE TABLE tbl_setlist_music (
          setlist_id NUMBER NOT NULL,
          music_id NUMBER NOT NULL,
          track_number NUMBER NOT NULL,
          CONSTRAINT pk_setlist_music PRIMARY KEY (setlist_id,track_number),
          CONSTRAINT fk_sm_setlist
            FOREIGN KEY (setlist_id)
            REFERENCES tbl_setlists(setlist_id),
          CONSTRAINT fk_sm_music
            FOREIGN KEY (music_id)
            REFERENCES tbl_music(music_id)
        )
      `);
      console.log('Created tbl_setlist_music table');
    } catch (err) {
      if (err.errorNum === 955) {
        console.log('tbl_setlist_music table already exists');
      } else {
        throw err;
      }
    }

    try {
      await conn.execute(`
        CREATE TABLE tbl_tags (
          tag_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
          tag_name VARCHAR2(255) NOT NULL,
          note VARCHAR2(255),
          user_id NUMBER NOT NULL,
          created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
          deleted_at TIMESTAMP,
          CONSTRAINT pk_tags PRIMARY KEY (tag_id),
          CONSTRAINT fk_tag_users
            FOREIGN KEY (user_id)
            REFERENCES tbl_users(user_id),
          CONSTRAINT uq_tags_name UNIQUE (tag_name,user_id)
        )
      `);
      console.log('Created tbl_tags table');
    } catch (err) {
      if (err.errorNum === 955) {
        console.log('tbl_tags table already exists');
      } else {
        throw err;
      }
    }

    try {
      await conn.execute(`
        CREATE TABLE tbl_music_tags (
          music_id NUMBER NOT NULL,
          tag_id NUMBER NOT NULL,
          created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
          CONSTRAINT pk_music_tags PRIMARY KEY (music_id, tag_id),
          CONSTRAINT fk_mt_music
            FOREIGN KEY (music_id)
            REFERENCES tbl_music(music_id)
            ON DELETE CASCADE,
          CONSTRAINT fk_mt_tag
            FOREIGN KEY (tag_id)
            REFERENCES tbl_tags(tag_id)
            ON DELETE CASCADE
        )
      `);
      console.log('Created tbl_music_tags table');
    } catch (err) {
      if (err.errorNum === 955) {
        console.log('tbl_music_tags table already exists');
      } else {
        throw err;
      }
    }

    try {
      await conn.execute(`
        CREATE TABLE tbl_chords (
          chord_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
          chord_name VARCHAR2(20) NOT NULL,
          CONSTRAINT pk_chords PRIMARY KEY (chord_id),
          CONSTRAINT uq_chords_name UNIQUE (chord_name)
        )
      `);
      console.log('Created tbl_chords table');
    } catch (err) {
      if (err.errorNum === 955) {
        console.log('tbl_chords table already exists');
      } else {
        throw err;
      }
    }

    try {
      await conn.execute(`
        CREATE TABLE tbl_chord_progression (
          music_id NUMBER NOT NULL,
          chord_id NUMBER NOT NULL,
          absolute_tick NUMBER NOT NULL,
          CONSTRAINT pk_chord_progression PRIMARY KEY (music_id, absolute_tick),
          CONSTRAINT fk_cp_music
            FOREIGN KEY (music_id)
            REFERENCES tbl_music(music_id)
            ON DELETE CASCADE,
          CONSTRAINT fk_cp_chord
            FOREIGN KEY (chord_id)
            REFERENCES tbl_chords(chord_id)
        )
      `);
      console.log('Created tbl_chord_progression table');
    } catch (err) {
      if (err.errorNum === 955) {
        console.log('tbl_chord_progression table already exists');
      } else {
        throw err;
      }
    }

    try {
      await conn.execute(`
        CREATE TABLE tbl_group_members (
          group_id NUMBER NOT NULL,
          artist_id NUMBER NOT NULL,
          join_date DATE,
          leave_date DATE,
          CONSTRAINT pk_group_members PRIMARY KEY (group_id, artist_id),
          CONSTRAINT fk_gm_group
            FOREIGN KEY (group_id)
            REFERENCES tbl_groups(group_id)
            ON DELETE CASCADE,
          CONSTRAINT fk_gm_artist
            FOREIGN KEY (artist_id)
            REFERENCES tbl_artists(artist_id)
            ON DELETE CASCADE
        )
      `);
      console.log('Created tbl_group_members table');
    } catch (err) {
      if (err.errorNum === 955) {
        console.log('tbl_group_members table already exists');
      } else {
        throw err;
      }
    }

    // テストデータを挿入
    console.log('\nInserting test data...');

    // ユーザーが既に存在しないかチェック
    const checkUsers = await conn.execute(
      `SELECT COUNT(*) as cnt FROM tbl_users`,
      [],
      { outFormat: oracledb.OUT_FORMAT_OBJECT }
    );

    if (checkUsers.rows[0].CNT === 0) {
      await conn.execute(
        `INSERT INTO tbl_users (user_name, date_of_birth) VALUES (:name, :dob)`,
        { name: 'John Doe', dob: new Date('1990-01-15') },
        { autoCommit: true }
      );
      console.log('User inserted');
    }

    // クリエイター/アーティストが既に存在しないかチェック
    const checkCreators = await conn.execute(
      `SELECT COUNT(*) as cnt FROM tbl_creators`,
      [],
      { outFormat: oracledb.OUT_FORMAT_OBJECT }
    );

    if (checkCreators.rows[0].CNT === 0) {
      const soloArtists = [
        { name: 'Michael Jackson', type: 'SOLO' },
        { name: 'David Bowie', type: 'SOLO' },
        { name: 'Freddie Mercury', type: 'SOLO' }
      ];

      const groupCreators = [
        { name: 'The Beatles', type: 'GROUP' },
        { name: 'Queen', type: 'GROUP' },
        { name: 'Pink Floyd', type: 'GROUP' }
      ];

      // ソロアーティスト追加
      for (const artist of soloArtists) {
        await conn.execute(
          `INSERT INTO tbl_creators (creator_name, creator_type) VALUES (:name, :type)`,
          { name: artist.name, type: artist.type },
          { autoCommit: true }
        );
      }

      // グループクリエイター追加
      for (const group of groupCreators) {
        await conn.execute(
          `INSERT INTO tbl_creators (creator_name, creator_type) VALUES (:name, :type)`,
          { name: group.name, type: group.type },
          { autoCommit: true }
        );
      }

      console.log('Creators inserted');

      // アーティスト情報を追加
      const soloResult = await conn.execute(
        `SELECT creator_id, creator_name FROM tbl_creators WHERE creator_type = 'SOLO'`,
        [],
        { outFormat: oracledb.OUT_FORMAT_OBJECT }
      );

      for (const creator of soloResult.rows) {
        await conn.execute(
          `INSERT INTO tbl_artists (artist_id, artist_name, started_at) 
           VALUES (:id, :name, SYSDATE)`,
          { id: creator.CREATOR_ID, name: creator.CREATOR_NAME },
          { autoCommit: true }
        );
      }

      console.log('Artists inserted');

      // グループ情報を追加
      const groupResult = await conn.execute(
        `SELECT creator_id, creator_name FROM tbl_creators WHERE creator_type = 'GROUP'`,
        [],
        { outFormat: oracledb.OUT_FORMAT_OBJECT }
      );

      for (const creator of groupResult.rows) {
        await conn.execute(
          `INSERT INTO tbl_groups (group_id, group_name, formation_date)
           VALUES (:id, :name, SYSDATE)`,
          { id: creator.CREATOR_ID, name: creator.CREATOR_NAME },
          { autoCommit: true }
        );
      }

      console.log('Groups inserted');
    }

    // 曲が既に存在しないかチェック
    const checkSongs = await conn.execute(
      `SELECT COUNT(*) as cnt FROM tbl_music`,
      [],
      { outFormat: oracledb.OUT_FORMAT_OBJECT }
    );

    if (checkSongs.rows[0].CNT === 0) {
      const creatorsMap = await conn.execute(
        `SELECT creator_id, creator_name FROM tbl_creators`,
        [],
        { outFormat: oracledb.OUT_FORMAT_OBJECT }
      );

      const creatorMap = {};
      creatorsMap.rows.forEach(c => {
        creatorMap[c.CREATOR_NAME] = c.CREATOR_ID;
      });

      const songs = [
        { title: 'Thriller', creator: 'Michael Jackson', bpm: 82, key: 'E', duration: 294 },
        { title: 'Billie Jean', creator: 'Michael Jackson', bpm: 117, key: 'F#', duration: 294 },
        { title: 'Heroes', creator: 'David Bowie', bpm: 108, key: 'G', duration: 423 },
        { title: 'Space Oddity', creator: 'David Bowie', bpm: 96, key: 'D', duration: 301 },
        { title: 'Let It Be', creator: 'The Beatles', bpm: 127, key: 'C', duration: 243 },
        { title: 'Come Together', creator: 'The Beatles', bpm: 83, key: 'A', duration: 259 },
        { title: 'Bohemian Rhapsody', creator: 'Queen', bpm: 55, key: 'B', duration: 354 },
        { title: 'We Will Rock You', creator: 'Queen', bpm: 81, key: 'A', duration: 143 },
        { title: 'Wish You Were Here', creator: 'Pink Floyd', bpm: 81, key: 'E', duration: 296 },
        { title: 'Comfortably Numb', creator: 'Pink Floyd', bpm: 68, key: 'G#m', duration: 406 }
      ];

      for (const song of songs) {
        const creatorId = creatorMap[song.creator];
        if (creatorId) {
          await conn.execute(
            `INSERT INTO tbl_music (music_title, creator_id, bpm, musical_key, duration_seconds)
             VALUES (:title, :creator_id, :bpm, :key, :duration)`,
            {
              title: song.title,
              creator_id: creatorId,
              bpm: song.bpm,
              key: song.key,
              duration: song.duration
            },
            { autoCommit: true }
          );
        }
      }

      console.log('Songs inserted');
    }

    console.log('\n✅ Database initialized successfully!');

  } catch (err) {
    console.error('❌ Error:', err);
  } finally {
    if (conn) {
      try {
        await conn.close();
      } catch (err) {
        console.error('Error closing connection:', err);
      }
    }
  }
}

initializeDatabase();
