const fs = require('fs');
const path = require('path');
const db = require('./db');

// helper to translate Oracle DDL to Postgres-compatible syntax
function convertDDLForPostgres(sql) {
  let pg = sql;
  pg = pg.replace(/NUMBER GENERATED BY DEFAULT AS IDENTITY/gi, 'SERIAL');
  pg = pg.replace(/\bNUMBER\b/gi, 'INTEGER');
  pg = pg.replace(/VARCHAR2/gi, 'VARCHAR');
  pg = pg.replace(/SYSTIMESTAMP/gi, 'NOW()');
  // add IF NOT EXISTS to every CREATE TABLE
  pg = pg.replace(/CREATE TABLE\s+(\w+)/gi, 'CREATE TABLE IF NOT EXISTS $1');
  return pg;
}

async function initializeDatabase() {
  let conn;
  try {
    conn = await db.getConnection();
    const isPg = db.dbType === 'postgres';

    console.log(`Connected to ${db.dbType} database`);

    // load canonical DDL
    const ddlPath = path.join(__dirname, '..', 'doc', 'query.sql');
    let ddl = fs.readFileSync(ddlPath, 'utf8');

    if (isPg) {
      ddl = convertDDLForPostgres(ddl);
    }

    const statements = ddl
      .split(/;\s*(?:\r?\n)/)
      .map(s => s.trim())
      .filter(Boolean);

    for (const stmt of statements) {
      try {
        await conn.execute(stmt);
        const firstLine = stmt.split('\n')[0];
        console.log(`Executed: ${firstLine}`);
      } catch (err) {
        if (isPg && err.code === '42P07') {
          console.log('  (already exists)');
          continue;
        }
        if (!isPg && err.errorNum === 955) {
          console.log('  (already exists)');
          continue;
        }
        throw err;
      }
    }

    // insert some sample data if the tables are empty
    await insertTestData(conn);

    console.log('\n✅ Database initialized successfully!');
  } catch (err) {
    console.error('Error during initialization:', err);
  } finally {
    if (conn) await conn.close();
  }
}

async function insertTestData(conn) {
  const oracledb = db.oracledb;

  console.log('\nInserting test data...');

  const checkUsers = await conn.execute(
    `SELECT COUNT(*) as cnt FROM tbl_users`,
    [],
    { outFormat: oracledb.OUT_FORMAT_OBJECT }
  );

  if (checkUsers.rows[0].CNT === 0) {
    await conn.execute(
      `INSERT INTO tbl_users (user_name, date_of_birth) VALUES (:name, :dob)`,
      { name: 'John Doe', dob: new Date('1990-01-15') },
      { autoCommit: true }
    );
    console.log('User inserted');
  }

  const checkCreators = await conn.execute(
    `SELECT COUNT(*) as cnt FROM tbl_creators`,
    [],
    { outFormat: oracledb.OUT_FORMAT_OBJECT }
  );

  if (checkCreators.rows[0].CNT === 0) {
    const soloArtists = [
      { name: 'Michael Jackson', type: 'SOLO' },
      { name: 'David Bowie', type: 'SOLO' },
      { name: 'Freddie Mercury', type: 'SOLO' }
    ];

    const groupCreators = [
      { name: 'The Beatles', type: 'GROUP' },
      { name: 'Queen', type: 'GROUP' },
      { name: 'Pink Floyd', type: 'GROUP' }
    ];

    for (const artist of soloArtists) {
      await conn.execute(
        `INSERT INTO tbl_creators (creator_name, creator_type) VALUES (:name, :type)`,
        { name: artist.name, type: artist.type },
        { autoCommit: true }
      );
    }

    for (const group of groupCreators) {
      await conn.execute(
        `INSERT INTO tbl_creators (creator_name, creator_type) VALUES (:name, :type)`,
        { name: group.name, type: group.type },
        { autoCommit: true }
      );
    }

    console.log('Creators inserted');

    const soloResult = await conn.execute(
      `SELECT creator_id, creator_name FROM tbl_creators WHERE creator_type = 'SOLO'`,
      [],
      { outFormat: oracledb.OUT_FORMAT_OBJECT }
    );

    for (const creator of soloResult.rows) {
      await conn.execute(
        `INSERT INTO tbl_artists (artist_id, artist_name, started_at) 
           VALUES (:id, :name, ${db.dbType==='postgres' ? 'NOW()' : 'SYSDATE'})`,
        { id: creator.CREATOR_ID, name: creator.CREATOR_NAME },
        { autoCommit: true }
      );
    }

    console.log('Artists inserted');

    const groupResult = await conn.execute(
      `SELECT creator_id, creator_name FROM tbl_creators WHERE creator_type = 'GROUP'`,
      [],
      { outFormat: oracledb.OUT_FORMAT_OBJECT }
    );

    for (const creator of groupResult.rows) {
      await conn.execute(
        `INSERT INTO tbl_groups (group_id, group_name, formation_date)
           VALUES (:id, :name, ${db.dbType==='postgres' ? 'NOW()' : 'SYSDATE'})`,
        { id: creator.CREATOR_ID, name: creator.CREATOR_NAME },
        { autoCommit: true }
      );
    }

    console.log('Groups inserted');
  }

  const checkSongs = await conn.execute(
    `SELECT COUNT(*) as cnt FROM tbl_music`,
    [],
    { outFormat: oracledb.OUT_FORMAT_OBJECT }
  );

  if (checkSongs.rows[0].CNT === 0) {
    const creatorsMap = await conn.execute(
      `SELECT creator_id, creator_name FROM tbl_creators`,
      [],
      { outFormat: oracledb.OUT_FORMAT_OBJECT }
    );

    const creatorMap = {};
    creatorsMap.rows.forEach(c => {
      creatorMap[c.CREATOR_NAME] = c.CREATOR_ID;
    });

    const songs = [
      { title: 'Thriller', creator: 'Michael Jackson', bpm: 82, key: 'E', duration: 294 },
      { title: 'Billie Jean', creator: 'Michael Jackson', bpm: 117, key: 'F#', duration: 294 },
      { title: 'Heroes', creator: 'David Bowie', bpm: 108, key: 'G', duration: 423 },
      { title: 'Space Oddity', creator: 'David Bowie', bpm: 96, key: 'D', duration: 301 },
      { title: 'Let It Be', creator: 'The Beatles', bpm: 127, key: 'C', duration: 243 },
      { title: 'Come Together', creator: 'The Beatles', bpm: 83, key: 'A', duration: 259 },
      { title: 'Bohemian Rhapsody', creator: 'Queen', bpm: 55, key: 'B', duration: 354 },
      { title: 'We Will Rock You', creator: 'Queen', bpm: 81, key: 'A', duration: 143 },
      { title: 'Wish You Were Here', creator: 'Pink Floyd', bpm: 81, key: 'E', duration: 296 },
      { title: 'Comfortably Numb', creator: 'Pink Floyd', bpm: 68, key: 'G#m', duration: 406 }
    ];

    for (const song of songs) {
      const creatorId = creatorMap[song.creator];
      if (creatorId) {
        await conn.execute(
          `INSERT INTO tbl_music (music_title, creator_id, bpm, musical_key, duration_seconds)
             VALUES (:title, :creator_id, :bpm, :key, :duration)`,
          {
            title: song.title,
            creator_id: creatorId,
            bpm: song.bpm,
            key: song.key,
            duration: song.duration
          },
          { autoCommit: true }
        );
      }
    }

    console.log('Songs inserted');
  }
}

initializeDatabase();
