apiVersion: v1
kind: Secret
metadata:
  name: music-app-secret
type: Opaque
stringData:
  PG_USER: "your-user"
  PG_PASSWORD: "your-password"
  PG_DATABASE: "your-db"
  PG_HOST: "postgres"
  PG_PORT: "5432"
  PORT: "3000"
