CREATE TABLE tbl_users (
    user_id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    user_name VARCHAR(255) NOT NULL,
    date_of_birth DATE,
    CONSTRAINT pk_users PRIMARY KEY (user_id)
);

CREATE TABLE tbl_creators (
    creator_id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    creator_name VARCHAR(255) NOT NULL,
    creator_type VARCHAR(20) CHECK (creator_type IN ('SOLO','GROUP')),
    CONSTRAINT pk_creators PRIMARY KEY (creator_id)
);

CREATE TABLE tbl_artists (
    artist_id INTEGER NOT NULL,
    artist_name VARCHAR(255) NOT NULL,
    date_of_birth DATE,
    started_at DATE,
    ended_at DATE,
    CONSTRAINT pk_artists PRIMARY KEY (artist_id),
    CONSTRAINT fk_artist_creator
        FOREIGN KEY (artist_id)
        REFERENCES tbl_creators(creator_id)
        ON DELETE CASCADE
);

CREATE TABLE tbl_groups (
    group_id INTEGER NOT NULL,
    group_name VARCHAR(255) NOT NULL,
    formation_date DATE,
    dissolution_date DATE,
    CONSTRAINT pk_groups PRIMARY KEY (group_id),
    CONSTRAINT fk_group_creator
        FOREIGN KEY (group_id)
        REFERENCES tbl_creators(creator_id)
        ON DELETE CASCADE
);

CREATE TABLE tbl_music (
    music_id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    music_title VARCHAR(255) NOT NULL,
    creator_id INTEGER NOT NULL,
    lyrics_by INTEGER,
    composed_by INTEGER,
    arranged_by INTEGER,
    bpm INTEGER CHECK (bpm BETWEEN 20 AND 400),
    musical_key VARCHAR(5),
    duration_seconds INTEGER,
    CONSTRAINT pk_music PRIMARY KEY (music_id),
    CONSTRAINT fk_music_creator FOREIGN KEY (creator_id) REFERENCES tbl_creators(creator_id),
    CONSTRAINT fk_music_lyrics FOREIGN KEY (lyrics_by) REFERENCES tbl_creators(creator_id),
    CONSTRAINT fk_music_composed FOREIGN KEY (composed_by) REFERENCES tbl_creators(creator_id),
    CONSTRAINT fk_music_arranged FOREIGN KEY (arranged_by) REFERENCES tbl_creators(creator_id)
);

CREATE TABLE tbl_albums (
    album_id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    album_name VARCHAR(255) NOT NULL,
    creator_id INTEGER,
    release_date DATE,
    CONSTRAINT pk_albums PRIMARY KEY (album_id),
    CONSTRAINT fk_album_creators FOREIGN KEY (creator_id) REFERENCES tbl_creators(creator_id)
);

CREATE TABLE tbl_album_music (
    album_id INTEGER NOT NULL,
    music_id INTEGER NOT NULL,
    track_number INTEGER NOT NULL,
    CONSTRAINT pk_album_music PRIMARY KEY (album_id, track_number),
    CONSTRAINT fk_am_albums FOREIGN KEY (album_id) REFERENCES tbl_albums(album_id),
    CONSTRAINT fk_am_music FOREIGN KEY (music_id) REFERENCES tbl_music(music_id) ON DELETE CASCADE,
    CONSTRAINT uq_album_music UNIQUE (album_id, music_id)
);

CREATE TABLE tbl_user_owned_music (
    user_id INTEGER NOT NULL,
    music_id INTEGER NOT NULL,
    CONSTRAINT pk_user_owned_music PRIMARY KEY (user_id, music_id),
    CONSTRAINT fk_uom_users FOREIGN KEY (user_id)
        REFERENCES tbl_users(user_id) ON DELETE CASCADE,
    CONSTRAINT fk_uom_music FOREIGN KEY (music_id)
        REFERENCES tbl_music(music_id) ON DELETE CASCADE
);

CREATE TABLE tbl_setlists (
    setlist_id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    setlist_name VARCHAR(255) NOT NULL,
    user_id INTEGER NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    deleted_at TIMESTAMP,
    updated_at TIMESTAMP,
    CONSTRAINT pk_setlists PRIMARY KEY (setlist_id),
    CONSTRAINT fk_setlist_users FOREIGN KEY (user_id)
        REFERENCES tbl_users(user_id) ON DELETE CASCADE
);

CREATE TABLE tbl_setlist_music (
    setlist_id INTEGER NOT NULL,
    music_id INTEGER NOT NULL,
    track_number INTEGER NOT NULL,
    CONSTRAINT pk_setlist_music PRIMARY KEY (setlist_id, track_number),
    CONSTRAINT fk_sm_setlist FOREIGN KEY (setlist_id)
        REFERENCES tbl_setlists(setlist_id),
    CONSTRAINT fk_sm_music FOREIGN KEY (music_id)
        REFERENCES tbl_music(music_id) ON DELETE CASCADE
);

CREATE TABLE tbl_tags (
    tag_id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    tag_name VARCHAR(255) NOT NULL,
    note VARCHAR(255),
    user_id INTEGER NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    deleted_at TIMESTAMP,
    CONSTRAINT pk_tags PRIMARY KEY (tag_id),
    CONSTRAINT fk_tag_users FOREIGN KEY (user_id)
        REFERENCES tbl_users(user_id),
    CONSTRAINT uq_tags_name UNIQUE (tag_name, user_id)
);

CREATE TABLE tbl_music_tags (
    music_id INTEGER NOT NULL,
    tag_id INTEGER NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT pk_music_tags PRIMARY KEY (music_id, tag_id),
    CONSTRAINT fk_mt_music FOREIGN KEY (music_id)
        REFERENCES tbl_music(music_id) ON DELETE CASCADE,
    CONSTRAINT fk_mt_tag FOREIGN KEY (tag_id)
        REFERENCES tbl_tags(tag_id) ON DELETE CASCADE
);

CREATE TABLE tbl_chords (
    chord_id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    chord_name VARCHAR(20) NOT NULL,
    CONSTRAINT pk_chords PRIMARY KEY (chord_id),
    CONSTRAINT uq_chords_name UNIQUE (chord_name)
);

CREATE TABLE tbl_chord_progression (
    music_id INTEGER NOT NULL,
    chord_id INTEGER NOT NULL,
    absolute_tick INTEGER NOT NULL,
    CONSTRAINT pk_chord_progression PRIMARY KEY (music_id, absolute_tick),
    CONSTRAINT fk_cp_music FOREIGN KEY (music_id)
        REFERENCES tbl_music(music_id) ON DELETE CASCADE,
    CONSTRAINT fk_cp_chord FOREIGN KEY (chord_id)
        REFERENCES tbl_chords(chord_id)
);

CREATE TABLE tbl_group_members (
    group_id INTEGER NOT NULL,
    artist_id INTEGER NOT NULL,
    join_date DATE,
    leave_date DATE,
    CONSTRAINT pk_group_members PRIMARY KEY (group_id, artist_id),
    CONSTRAINT fk_gm_group FOREIGN KEY (group_id)
        REFERENCES tbl_groups(group_id) ON DELETE CASCADE,
    CONSTRAINT fk_gm_artist FOREIGN KEY (artist_id)
        REFERENCES tbl_artists(artist_id) ON DELETE CASCADE
);
